w3c/specberus

README.md
lib/rules/headers/dl.js

Metadata: added editor's draft

---

lib/rules/headers/dl.js
lib/rules/structure/h2.js
lib/rules/style/sheet.js
lib/validator.js
package.json

This fixes #152.
The latest API allows us to get rid of some hacks, which is always nice :-)

Update whacko and remove old hacks

---

lib/rules/headers/translations.js
test/all-rules.js
test/docs/headers/translations-alternative.html

Allow `2005/11/Translations` links

---

public/css/specberus.css
public/index.html

[Discussed inline](https://github.com/w3c/specberus/pull/180/files#r28079011).

Add link to pubrules in header logo (follow-up #180)

---

README.md
package.json

Add description to the package information

---

package.json

See https://github.com/w3c/echidna/pull/170

Dependency versions redesign

---

lib/l10n-en_GB.js
lib/l10n-es_ES.js
lib/l10n.js
public/index.html

* Remove trailing slashes in HTML (`/>`).
* Remove `shortcut` rel from *favicon* link.
-- 
See comments: [this](https://github.com/w3c/specberus/pull/199#discussion_r30607285) and [this](https://github.com/w3c/specberus/pull/199#discussion_r30608040).

Polish HTML coding style

---

README.md

&hellip;now that Specberus is an npm package.

Update wording about npm

---

.travis.yml
package.json

Run [`nsp audit-package`](https://github.com/nodesecurity/nsp#nsp-audit-package) during the CI cycle.

Check dependencies against nodesecurity.io DB as part of CI

---

.travis.yml

As explained [here](http://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F).

Have Travis use containers to build (modern infrastructure)

---

.travis.yml

What @astorije did in w3c/echidna#208, plus his comment [here](https://github.com/w3c/echidna/pull/204#discussion_r34558952).

Travis: fix a couple of details in the config file

---

lib/rules/validation/css.js
lib/rules/validation/html.js
lib/validator.js
package.json

The history of commits is a bit messy; better to examine only the final diff.

Upgrade Superagent; fix nsp error

---

lib/l10n-en_GB.js
lib/l10n-es_ES.js
lib/rules/headers/dl.js

If the previous and latest versions don't match, check if it's a same day publication.
Fix #190

Same day publication

---

.travis.yml

&hellip;[as @astorije suggested](https://github.com/w3c/echidna/pull/210#discussion_r35340426).

Travis: move “nsp” to “script” section

---

public/js/specberus.js

Fix profile selection when the profile query param is provided

---

lib/rules/sotd/pp.js

See https://github.com/w3c/specberus/pull/222#discussion-diff-36378123

Refined https regex

---

README.md
lib/l10n-en_GB.js
lib/l10n-es_ES.js
lib/rules/sotd/process.js
public/index.html
test/all-rules.js
test/docs/sotd/deprecated.html
test/docs/sotd/process2015.html
test/docs/sotd/wrongprocess.html

As per [proposed process 1 September 2015](http://www.w3.org/2015/Process-20150901/).
See also [the roll-out plan](https://www.w3.org/Team/wiki/Process2015#Echidna_.26_Specberus).
This addresses #218.
This PR is intended as a place for tests and discussion for a while.
:warning: **Do not merge until 1 Sep 2015.**

Adapt code to Process 2015

---

lib/rules/headers/dl.js

Fix https://github.com/w3c/echidna/issues/201

metadata sanitization

---

.travis.yml

See #237.
(Also, stop Travis from sending e-mail notifications to me.)

Update npm key in Travis config

---

lib/l10n-en_GB.js
lib/l10n-es_ES.js
lib/rules/headers/copyright.js
test/all-rules.js
test/docs/headers/permissive-doc-license.html

Allow the use of the permissive document license in the copyright

---

lib/rules/sotd/pp.js

Fix https://github.com/w3c/echidna/issues/226

pp text is now a regexp to have more flexibility

---

public/js/specberus.js

reset the result summary before running a new validation

---

README.md
app.js
lib/profiles/FPCR.js
public/data/profiles.json
public/js/specberus.js

@plehegar that MR adds a new profile (`First Public Candidate Recommendation`) to specberus according to process 2015.
Let me know if you are ok the name of the profile (appearing in the `<h2>`).

New profile: First Public Candidate Recommendation

---

lib/exceptions.json

Based on css errors from the latest CSS UI CR.

Ignore at-rule errors from css-ui-3

---

README.md
app.js
lib/profiles/FPCR.js
public/data/profiles.json
public/js/specberus.js

I merged #264 too happily.
Now undoing the merge, and submitting this for @plehegar's review again.
Please refer to the discussion on the original PR.

New profile: First Public Candidate Recommendation [bis]

---

package.json

Revert PR #268 (ms vulnerability issue)

---

lib/l10n-en_GB.js
lib/l10n-es_ES.js
lib/profiles/base.js
lib/rules/style/meta.js
package.json
test/all-rules.js
test/docs/style/simple.html
test/docs/style/wrong-meta.html

Check new tag <meta name="viewport">

---

lib/l10n-en_GB.js
lib/l10n-es_ES.js
lib/profiles/base.js
lib/rules/headers/ol-toc.js
test/all-rules.js
test/docs/headers/proper-toc.html

NB: throws only a warning if not found, ie this rule does *not* fail.
cf. #267.

Check new expected element <ol class="toc">

---

lib/validator.js
test/docs/headers/simple.html

Fix #290 
**Do not merge before Feb 29**

fix SotD detection after the 2016 TR design

---

lib/rules/sotd/pp.js
lib/validator.js
public/js/specberus.js

Fix options passed from the form

---

lib/exceptions.json

This might or might not be the correct syntax. :)

Update exceptions for "powerful-features"

---

lib/rules/style/sheet.js

check if there's no internal stylesheets after the TR stylesheet

---

lib/l10n-en_GB.js
lib/l10n-es_ES.js
lib/rules/headers/dl.js
lib/rules/heuristic/shortname.js
test/docs/headers/diff-latest-version.html
test/rules.js

Latest version can be different for multi level documents

---

lib/l10n-en_GB.js
lib/l10n-es_ES.js
lib/rules/sotd/implementation.js

implementation rule: check if SotD exists

---

public/css/specberus.css
public/js/specberus.js

Also, avoid flickering of extended options.
cv #335.

Fix issue of "auto" profile not selected by default in Chrom*

---

app.js
lib/validator.js
public/css/specberus.css
public/index.html
public/js/specberus.js

This PR relies on https://github.com/w3c/specberus/pull/331 to get all the options needed to validate a document.
Fix #302

New profile 'auto' using `extractMetadata` to grab the options

---

package.json

chore(package): update socket.io to version 1.4.6

---

lib/api.js
lib/util.js
lib/validator.js
test/api.js
test/rules.js

With this PR, both `validate()` and `extractMetadata()` return an `Object` with the usual fields
(`success`, `errors`, `warnings`, `info` and `metadata`).

Both methods should return Object with all data

---

views/index.handlebars

Tweak Bootstrap spacing after deleting some of the inputs in the form

---

lib/rules/sotd/pp.js

pp: remove backslashes from expected text

---

README.md
lib/validator.js
lib/views.js
public/js/specberus.js
views/doc/index.handlebars
views/doc/rules/index.handlebars
views/error.handlebars
views/help.handlebars
views/index.handlebars
views/layouts/main.handlebars
views/sitemap.handlebars
views/wip.handlebars

Use env var “BASE_URI” for links/routes instead of assuming root dir

---

lib/profiles/WG-NOTE-Echidna.js
public/js/specberus.js

Also, fix codename of Echidna-flavoured &ldquo;WG Note&rdquo; profile.

Fix “see rule in context” links for profiles “*-echidna”

---

lib/l10n-en_GB.js
lib/l10n-es_ES.js
lib/profiles/PER.js
lib/profiles/PR.js
lib/profiles/TR.js
lib/profiles/base.js
lib/rules/dummy/dahut.js
lib/rules/dummy/h1.js
lib/rules/dummy/h2-foo.js
lib/rules/headers/copyright.js
lib/rules/headers/div-head.js
lib/rules/headers/dl.js
lib/rules/headers/title.js
lib/rules/sotd/process-document.js
test/api.js
test/l10n.js
test/rules.js

Automatically check rule IDs, lib/rules/ files and L10n strings

---

lib/l10n-en_GB.js

specify timezone in the rule echidna.todays-date

---

lib/l10n-en_GB.js
lib/rules/links/compound.js
lib/rules/validation/css.js
lib/rules/validation/html.js

if the HTML/CSS validators are timing out, send a warning and consider the rule OK

---

lib/rules/sotd/mailing-list.js

Look for a GitHub repository, and qualify the ML/subscribe checks accordingly

---

lib/rules/heuristic/date-format.js
test/docs/heuristic/bad-dates.html

look for dates in div.head and sotd only

---

.nsprc
lib/rules/sotd/group-homepage.js
test/docs/sotd/group-homepage-https.html
test/rules.js

group homepage can be on http or https

---

lib/l10n-en_GB.js
lib/rules/links/compound.js

This closes #428 and closes #441

Fix compound validation bug

---

lib/l10n-en_GB.js
lib/rules/links/linkchecker.js

Avoid redundancy in two messages

---

lib/l10n-en_GB.js
lib/rules/structure/display-only.js
views/index.handlebars
views/layouts/main.handlebars

**Hold until deployment on 1 Aug 2016**
Fix first item of #418.

[On hold] Remove notice about Specberus being experimental etc

---

public/js/specberus.js

Specberus doesn't work on Safari 9 (current stable).
Fix #481

safari fix

---

lib/l10n-en_GB.js
lib/l10n.js
public/css/specberus.css

Fix error “could not interpolate variable ‘line’”

---

lib/l10n-en_GB.js
lib/rules/links/compound.js
lib/rules/validation/css.js

The css3svg profile is a superset of the CSS3 one that includes SVG properties.

change default profile for the CSS Validator to css3svg

---

lib/validator.js

Improve SotD detection

---

views/doc/index.handlebars

Better link to use than the current one

Use latest version link to transition requirements

---

public/js/specberus.js
views/index.handlebars

@deniak, what do you think of this solution over #487?
Can you try on your FF (also when typing a new URL on the address bar, etc)?

Better handling of socket disconnection

---

lib/rules/links/compound.js

fix recursive validation

---

lib/l10n-en_GB.js
lib/rules/headers/copyright.js
test/rules.js

Probably fixes https://github.com/w3c/specberus/issues/493 at the same time...

Remove warning when using permissive licence

---

lib/l10n-en_GB.js
lib/profiles/CR.js
lib/profiles/PR.js
lib/profiles/WD.js
lib/rules.json
lib/rules/structure/security-privacy.js

Docs should have a security and privacy considerations section

---

.gitignore
README.md
lib/rules/metadata/profile.js
test/docs/metadata/cr-mediacapture-streams.html
test/docs/metadata/pr-media-source.html
test/rules.js
test/samples.json

[metadata] PR and PER review date

---

lib/exceptions.json

@tabatkins asked to add an exception on the CSS errors for css-tables-3

ignore some CSS errors for css-tables-3

---

lib/rules/structure/security-privacy.js

This fixed a bug in the detection of the privacy section

Properly detect the privacy section

---

.travis.yml
package.json

* Travis notifications on IRC: one line; less noise.
* Update `express` (tested).
* Avoid ambiguous package versions.

Various minor changes

---

lib/exceptions.json

ignore CSS error at-rule

---

lib/rules/headers/errata.js

Relax the errata rule

---

lib/rules/sotd/pp.js

Notes are informative implicitly. No need to mention it in the SotD

---

lib/profiles/TR/IG-NOTE.js
lib/rules/sotd/pp.js
lib/validator.js
test/docs/headers/ig-note.html
test/rules.js

check specific requirements for IG notes

---

lib/rules/headers/dl.js
test/docs/headers/shortnameChange.html
test/rules.js

When a shortname change is detected, don't check the latest version link

---

package.json

fix(package): update promise to version 7.3.1

---

lib/rules/sotd/pp.js

Make PP regex for joint publications less restrictive

---

.nsprc

After merging, please:
```bash
npm version patch
git push --follow-tags
npm publish
```

nsp exceptions: https://nodesecurity.io/advisories/528 is fixed

---

.gitignore
README.md
lib/rules/metadata/profile.js
lib/rules/sotd/implementation.js
test/rules.js
test/samples.json

metadata should provide the implementation report when possible

Implementation report in metadata

---

README.md
lib/profiles/TR/CR-Echidna.js
public/js/specberus.js

@tripu this is the new profile we need to check to publish CR in echidna

new profile for CR in Echidna

---

lib/l10n-en_GB.js
lib/rules/sotd/cr-end.js
lib/validator.js
test/rules.js

The minimum review period for CR and PR is 28 days per https://www.w3.org/2018/Process-20180201/.
That PR retrieves only dates between the publication date +28 days and +1 year.
Also, for CR updates with editorial changes, we don't need to check that date so we simply skip the rule.

min review date is 28 days + handle editorial updates

---

lib/validator.js

string.match(regexp) returns null if no match

---

lib/rules.json
views/layouts/main.handlebars

[Rule #fixupJs](https://www.w3.org/pubrules/doc/rules/?profile=REC#fixupJs)
cf https://github.com/w3c/specberus/pull/297#issuecomment-427820666
/cc @Mouvedia

Suggest a <script> block that works for XHTML5, too

---

lib/exceptions.js
lib/exceptions.json

That PR adds an exception for wpub
Closes https://github.com/w3c/echidna/issues/596

wpub exception

---

README.md
lib/rules/metadata/dl.js
lib/rules/sotd/group-homepage.js
lib/validator.js

rename API_KEY var

---

lib/rules.json

* Fix typo in rule documentation (introduced by me in #776)

Miscellaneous fixes

---

lib/views.js

add link to github on front page.

add link to github

---

lib/exceptions.json

[[
Error: CSS: caret-shape: Property caret-shape doesn't exist.
]]
when checking the css-ui-4 document: https://validator.w3.org/nu/?doc=https%3A%2F%2Fdrafts.csswg.org%2Fcss-ui-4%2F
/cc @plehegar @deniak

css-ui-4 uses the caret-shape property

---

package.json

chore(package): update coveralls to version 3.1.0

---

lib/api.js
lib/sink.js
lib/validator.js
package.json

fix(package): update express-handlebars to version 4.0.3

---

lib/profiles/TR/IG-NOTE-Echidna.js
public/js/specberus.js

enable echidna check for IG-Notes

---

lib/rules/structure/h2.js
test/docs/structure/h2-abstract.html

Remove unnecessary h2 from .head to get right H2 list

---

lib/l10n-en_GB.js
lib/rules/headers/dl.js
lib/rules/headers/errata.js
lib/rules/sotd/implementation.js
lib/validator.js
test/docs/headers/dl-order.html
test/docs/headers/simple-oxford.html
test/docs/headers/simple.html
test/docs/headers/wg-note.html
test/docs/sotd/pp-bad.html
test/docs/sotd/supersedable.html
test/rules.js

Add https check for links

---

lib/rules/validation/css.js

ignore all errors in https://www.w3.org/StyleSheets/TR/2016/base.css

---

lib/profiles/TR/FPIG-NOTE.js
lib/profiles/TR/FPWG-NOTE.js

Remove diff check for FP-Notes.

---

lib/rules/metadata/patent-policy.js

Fix member submission stuck

---

lib/rules/heuristic/date-format.js
test/docs/heuristic/bad-dates.html
test/rules.js

Clearify date regular expression

---

lib/l10n-en_GB.js
lib/profiles/base.js
lib/rules/links/reliability.js
test/docs/links/internal-fails.html
test/rules.js

Add link check

---

lib/rules/sotd/supersedable.js

Fix app crashed situation

---

.gitignore
.istanbul.yml
.nycrc
package.json

Closes https://github.com/w3c/specberus/issues/981

chore: Convert Istanbul to NYC

---

.github/workflows/node.js.yml
package.json

Alternately, this could be split out to a separate job that only runs if affected files are touched

chore: Setup Coveralls in CI

---

.github/workflows/node.js.yml

Sorry, tested this one better by temporarily removing the push filter and testing on my fork  https://github.com/nschonni/specberus/actions/runs/288804993

fix: conditional secret check

---

lib/rules/metadata/profile.js

Throw error when doc is neither TR nor MEM-SUBM

---

views/doc/index.handlebars

remind people of the good stuff in /Guide

make link to Guide more descriptive

---

lib/rules/headers/mailing-list.js

Allow linking to a specific label in issues as well.

---

lib/rules/sotd/stability.js
test/docs/headers/ig-note.html

Relax stability rules, allowing more sentence at begining paragraph.

---

lib/rules/headers/mailing-list.js
test/rules.js

Require GH for all documents

---

lib/api.js
lib/l10n.js
lib/util.js
lib/validator.js

Add error detail for API result

---

lib/rules/sotd/pp.js
lib/util.js
lib/validator.js
test/docs/headers/wd.html
test/rules.js

Skip patent policy check for publications from TAG

---

lib/l10n.js

Resolve pubrules result info shows "undefined"

---

.jshintrc
lib/l10n-en_GB.js
lib/rules/sotd/pp.js
lib/validator.js
test/docs/sotd/wg-note-IG-bad.html
test/docs/sotd/wg-note-IG-good.html
test/rules.js

resolves #1041, resolves #1015, closes #1040 for too many commits.

Add IG REC-track check; Upgrade to ES8; Fix indentation

---

lib/validator.js

Fix crush for null.length

---

lib/rules.json
lib/rules/links/linkchecker.js

Allow document from other server, add allow list for document rule

---

lib/rules.json
lib/validator.js

Change data-deliverer attribute of joint publication

---

lib/l10n-en_GB.js
lib/rules/sotd/pp.js

Combine patent policy error message with advice

---

lib/rules/links/reliability.js
lib/rules/metadata/rectrack.js
test/docs/links/internal-fails.html
test/rules.js

Add tools.ietf.org to unreliable service

---

.github/workflows/js-lint.yml
.github/workflows/node.js.yml
package.json

Upgrade to Node@16

---

lib/rules/metadata/deliverers.js
lib/rules/metadata/patent-policy.js
lib/rules/sotd/charter-disclosure.js
lib/rules/sotd/group-homepage.js
lib/rules/sotd/pp.js
lib/validator.js
test/docs/sotd/pp-20200915-iprlink.html
test/rules.js

allow new IPR link instead of pp-impl link

---

lib/l10n-en_GB.js
lib/rules/metadata/profile.js
lib/validator.js

Give out error if the h2 profile cannot be found

---

lib/l10n-en_GB.js
public/js/specberus.js

Fix error message for double negative, add patent policy default value: pp2020

---

lib/rules/metadata/profile.js

Add better error message for ED

---

lib/l10n-en_GB.js
lib/rules/sotd/charter-disclosure.js

Check whether publisher has a living charter.

---

lib/rules/links/linkchecker.js

Allow everything under https://test.csswg.org/harness/

---

lib/rules.json
lib/rules/headers/mailing-list.js

Separate mailing list warning and github issue error

---

lib/l10n-en_GB.js
lib/rules/headers/secno.js
test/docs/headers/proper-secno.html

fix(rules/headers/secno): support bdi element

---

lib/rules/links/linkchecker.js
test/docs/links/external-resources.html

Add data: to the external allow list to allow inline svg

---

README.md

Add API explanation to README

---

lib/rules.json

That PR adds/updates the rules for the process 2021

Process 2021 doc

---

.eslintrc.json
lib/util.js

Turned the rule back on and fixed the instances

chore: fix ESLint no-continue

---

lib/rules/structure/neutral.js

any check shouldn't change the origin document, closes #1463

Fix node removal in neutral.js

---

.cspell.json
.editorconfig
.eslintrc.json
.github/dependabot.yml
.github/workflows/cspell-problem-matcher.json
.github/workflows/js-lint.yml
.github/workflows/node.js.yml
.gitignore
.prettierignore
README.md
doc/Presentation.md
jsdoc.json
lib/exceptions.js
lib/exceptions.json
lib/rules.json
lib/rules/headers/dl.js
lib/rules/structure/display-only.js
nodemon.json
package.json
public/badterms.json
public/css/specberus.css
tools/fetch-groups-db.js
tools/groups-sparql.json

Run on all the repo files except the HTML and handlebars files.
Include it in the commit hooks and CI

chore: Run prettier formatting outside ESLint

---

lib/exceptions.json
lib/profiles/base.js
lib/validator.js

Add copyright exception for security-privacy-questionnaire

---

lib/rules/sotd/publish.js

Improve publish.js rule, add IG and (TAG)

---

lib/exceptions.js
lib/l10n.js
lib/rules/links/linkchecker.js
lib/rules/metadata/profile.js
lib/rules/sotd/obsl-rescind.js
lib/rules/sotd/pp.js
lib/rules/sotd/rec-addition.js
lib/rules/sotd/stability.js
lib/rules/sotd/submission.js
lib/throttled-ua.js
lib/util.js
lib/validator.js
tools/fetch-groups-db.js

Autoscaffolded with `npm lint fix` and added some details

doc: update JSDoc blocks

---

views/doc/index.handlebars

Revert "fix: relative path before BASE_URI"

---

lib/rules/headers/copyright.js
lib/rules/sotd/charter.js
lib/validator.js

resolves #1508 , resolves https://github.com/w3c/specberus/issues/1378, and resolves https://github.com/w3c/specberus/issues/1377

Skip copyright and charter check for TAG and AB

---

lib/profiles/TR/Recommendation/REC-Echidna.js
public/js/specberus.js

That PR adds a new profile to be used with Echidna. See https://github.com/w3c/echidna/issues/1048

Echidna profile for REC with candidate amendments

---

.github/dependabot.yml

... leaving major upgrades only.

Ignore some dev-dependencies' minor upgrades

---

.github/workflows/node.js.yml
package.json

add node 18, remove node 14

---

lib/api.js

wait for promise to finish when processing params

---

lib/validator.js

Check editors draft with exact words, resolves https://github.com/w3c/specberus/issues/1714

Check editors draft with exact words

---

lib/l10n-en_GB.js
lib/rules/style/sheet.js
test/data/specBase.js
test/doc-views/layout/spec.handlebars
test/doc-views/specBase.js

fix rule related to the dark mode stylesheet

---

lib/profiles/TR/Registry/DRY-Echidna.js
public/js/specberus.js

That PR adds a profile to check draft registries with the echidna configuration

add profile for DRY-Echidna

---

lib/l10n-en_GB.js
lib/profiles/TR/Note/STMT.js
lib/profiles/TR/Recommendation/REC.js
lib/rules.json
lib/rules/headers/translation.js
test/data/TR/Note/STMT.js
test/data/TR/Recommendation/REC.js
test/doc-views/TR/Note/STMT.js
test/doc-views/TR/Recommendation/REC.js
test/doc-views/layout/spec.handlebars

@xueyuanjia, @plehegar, @koalie, this is the PR to require a link to the translation page for RECs and Statements.
FYI, I'm going to deploy it on Monday.

Make sure RECs and Statements have a link to the their translations

---

lib/rules.json

fix rules documentation for Notes
