w3c/specberus

lib/l10n.js, lib/profiles/base.js, lib/rules/structure/display-only.js
I feel there's still some confusion regarding [issues with the label `display-only`](https://github.com/w3c/specberus/labels/display-only). As the label indicates, those should be resolved simply by displaying a particular message to the user, ie not performing any validation. However, there are comments in some of those issues, along the lines of *&ldquo;Too Complex. Leave for v1.5&rdquo;* or *&ldquo;Is this implemented yet?&rdquo;*, which suggest some of the solutions might not be trivial. (?)
In any case, either to *solve* these issues, or simply to *patch* them temporarily until they're properly addressed, I've added a new *pseudo-rule* that will contain all those boilerplate messages.
These three are covered right now:
* #92.
* #96.
* #99.
=> Added new pseudo-rule “display-only”, including 3 informative messages

README.md, lib/l10n.js, lib/rules/headers/dl.js, lib/rules/heuristic/group.js, test/docs/headers/dl-mismatch.html, test/docs/headers/dl-order.html, test/docs/headers/simple.html
* Changed metadata key `groups` &rarr; `deliverers`.
* Value of metadata `deliverers` now is not an `Object`, but an `Array`. Each element of the array has keys `homepage` and `name`.
* Changed language about metadata `previousVersion` in `README.md`: *&ldquo;URL of the previous version of the document (the last one, if multiple are shown)&rdquo;*.
* Now, the ID(s) of editor(s) on the document **must** match *regex* `/\d+/`. Otherwise, it's not considered valid, **and a validation error is thrown**. Updated accordingly `README.md` and sample documents for testing. Also, the error message to the user now specifies that particular restriction.
=> Various fixes and improvements to metadata

lib/l10n.js, lib/rules/sotd/process.js
This fixes #126 by making Specberus return the URL for the process rules instead the text.
Since mentioning the process in the documents is rather new, I took the liberty to add the following things, based on what I could see when publishing:
- It checks that the governing process statement is specified only once
- It informs the user with more details when the process is not the right one
- It informs the user with more details when the link to the process is wrong
Do you plan to have the process detected automatically in the future (rather than through the options)? If so, then the `wrong-process` error will be pointless :)
=> Process detection improvements

README.md, lib/profiles/TR.js, lib/rules/headers/dl.js, lib/rules/heuristic/group.js, lib/rules/sotd/pp.js, lib/validator.js, public/index.html
We haven't reached consensus in #130. But @deniak and I favoured reading a new attribute `data-deliverer-id` on documents, and it's the quickest solution for the issue. So here is that solution.
For more info about how those IDs are being returned now, see [the updated documentation](https://github.com/w3c/specberus/blob/tripu/issue-130-deliverers-metadata/README.md#emitting-metadata-about-the-document).
Also, notice that the new attribute **is not required** by Specberus, ie not finding it on the document will *not* throw an error.
=> Deliverers' ID attribute recognised by Specberus, and spat out as part of metadata

lib/rules/headers/dl.js, lib/rules/sotd/pp.js
This adds a decimal base to calls to `parseInt`.
Rationale is explained at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt.
=> Add radix to parseInt calls

public/data/profiles.json, public/index.html, public/js/specberus.js
Fixes #51. (Necessary/convenient to tackle the addition of `status` to the metadata returned by Specberus.)
* Tracks and profiles are now loaded using a `GET` request for a new local JSON file, and the `<select>` input gets populated from that data.
* Fixed a bug: the value of CG notes was `FPWG-NOTE` by mistake.
* The *prompt* message of the `<select>` input is now non-selectable.
=> Retrieve the hierarchy of tracks and profiles in the UI from a new JSON file

README.md, lib/rules/headers/h2-status.js
=> Return “status” (a “String”) as part of metadata; update documentation accordingly

lib/rules/headers/dl.js
See [@astorije's comment](https://github.com/w3c/echidna/pull/39#issuecomment-71855010).
Here I could only restrict it to HTTP (no SSL). It's already requiring `www.`, and it's case-sensitive. Comments welcome.
=> W3C prefix: make regex as strict as possible

app.js, package.json
I updated the version of mocha and fixed the patch versions as discussed in #148.
I didn't update the non-dev dependency versions as all of them raised errors.
For example, `superagent` > `0.17.x` raises this 3 times:
```bash
`Request#part()` is deprecated. Pass a readable stream in to `Request#attach()` instead.
The `Part()` constructor is deprecated. Pass a readable stream in to `Request#attach()` instead.
Category validation Rule css should pass for validation/simple.html:
Uncaught TypeError: setting custom form-data part headers is unsupported
at deprecated.Part.set ([...]/specberus/node_modules/superagent/lib/node/part.js:58:9)
at addPart ([...]/specberus/lib/rules/validation/css.js:26:14)
at Object.exports.check ([...]/specberus/lib/rules/validation/css.js:39:9)
at …
```
=> Update dependency versions

README.md
* Recovered 2 lines that were mistakenly removed in ca435e3.
* Updated documentation to reflect the preferred use of `npm start [ARGS…]`.
=> Two minor fixes about documentation

.travis.yml
The `skip_join` part reflects [Echidna's `.travis.yml`](https://github.com/w3c/echidna/blob/master/.travis.yml) and saves us a few lines on IRC whenever someone pushes a commit...
If you're okay with that, I'll change the GitHub's bot configuration accordingly.
=> Changes to the Travis configuration

app.js, lib/l10n.js, lib/profiles/WD-Echidna.js, lib/rules/echidna/editor-ids.js, lib/rules/echidna/todays-date.js, lib/rules/headers/dl.js, public/index.html, public/js/specberus.js, test/all-rules.js, test/docs/echidna/automated-wg.html, test/docs/echidna/fails-future-date.html, test/docs/echidna/fails-missing-editorsid.html, test/docs/headers/dl-mismatch.html, test/docs/headers/dl-order.html
This adds an Echidna-specific profile, checking that the document being checked:
- has `data-editor-id` attributes for the editors
- is set at today's date
It comes with a few tests. I couldn't find a way to automate tests that the current date passes the checker. If you have suggestions, I'm all ears, otherwise I tested manually and it passes...
On top of the usual review, let me know if names and file organization is fine as I am not used to Specberus (@darobin++ for the architecture, btw!) yet.
Once you are okay with the inner changes, I will add the UI part so that people can use Specberus with Echidna profile(s). Makes sense?
=> Make an Echidna-specific profile for WDs

.gitignore, .travis.yml, README.md, package.json
- Sorry @tripu, I took the liberty to merge #154 myself, but I had a good intention: it wasn't compatible with this current PR and I merged it only so that I could `rebase` this one before you woke up and so that you can merge and release without conflicts :-)
- Code coverage can be run via `npm run coverage`, thanks to `istanbul`.
- The README badge for code coverage is updated after Travis builds, via the command above and `coveralls`, so no need to worry about this :)
- Travis also takes care of automatically deploying on [npm](https://www.npmjs.com/~w3c) after a successful build, only when a new tag is pushed. To publish, [according to the doc](http://docs.travis-ci.com/user/deployment/npm/), one must:
1. Have a clean repo (aka no changes that are uncommitted)
2. Run `npm version …
=> Code coverage and automatic publishing on npm

lib/rules/echidna/editor-ids.js
I learned that `toArray()` is deprecated in favor of `get()` by [requesting its documentation](https://github.com/cheeriojs/cheerio/issues/684).
Internally, `toArray()` just calls `get()` so we are not gaining anything but avoiding potential deletion of `toArray()` in a soon future.
=> Replace cheerio's deprecated toArray() with get()

lib/l10n.js, lib/rules/echidna/todays-date.js
This extends #159 by leaving the function type safe, fixing the function as it was mutating the source `Date` object, and adding a check/error if the date cannot be extracted from the document.
=> Fix the today's date check

lib/validator.js, public/js/specberus.js
Now that Echidna and Specberus are live, and as we fix bugs and deploy new versions (hopefully at a good pace), it becomes more important that users see clearly what versions of both pieces of software they are using. Someone reporting an issue, or asking for help, should be able to tell easily the exact versions that aren't working for her.
Specberus is already exposing its version through its API (and I plan to read that from Echidna soon, to append that info to the logs). However, on the web interface this information appears small and dim.
This PR makes it more visible, and adds the version to the `<title>` element too.
=> Make the version be more prominent in the UI

app.js, package.json
Hi,
Specberus was using the safe url input checker module (to check if an url is well formed on the server side) which is deprecated.
Instead, I wrote a new Promise based API more efficient: [insafe](http://github.com/w3c/insafe) and implemented it in Specberus.
=> implement insafe instead of safe-url-input-checker module

lib/rules/headers/copyright.js, lib/validator.js
@darobin, does that match [what you meant](https://github.com/w3c/specberus/issues/155)?
I think I'd like to see this feature also handle changes that do not need a transition periods, if it ever happens. Do you see how we could adapt this wording to deal with that as well?
Also, do you think we need to add any check on the input, what's stored in `options` (`from` and `to` are `Date` objects, `do*` are `function` values, ...)?
Once this is final and merged, and you have reached a conclusion on spec-prod, I will use this for #155.
=> Add a transition period feature

lib/rules/sotd/mailing-list.js
=> mailing list: the text content of `<a>` doesn't need to match the name of the mailing list

lib/l10n-en_GB.js, lib/l10n-es_ES.js, lib/rules/headers/dl.js, package.json, test/all-rules.js, test/docs/headers/wrong-urls.html
I'm comparing the *contents* (the actual documents) of "previous" vs. "latest"
&hellip;but just the *URLs* of "this" vs. "previous".
I understand that is what will guarantee that we're catching all those tricky situations explained in issue #29&hellip;? I have also extended the tests to try to catch these cases.
(@plehegar, it'd be great if you want to extend the Echidna test suite to cover these cases, once/if this is merged :¬)
=> Check against inconsistencies in URLs of this/previous/latest versions

lib/rules/heuristic/date-format.js, test/all-rules.js, test/docs/heuristic/dated-url.html
Suggesting tiny improvements over #185:
* Exclude URLs in uppercase, too (eg `HTTP://...`).
* Add to sample doc more varied examples of excluded dates in URLs.
* Fix coding style (move comma to the beginning of next line).
=> Improve #185

lib/rules/heuristic/date-format.js, test/all-rules.js, test/docs/heuristic/dated-url.html
This doesn't fix everything, in particular it doesn't solve[@darobin's last comment on the subject](https://github.com/w3c/specberus/issues/178#issuecomment-91503953), but this provides a quick fix for #178 until something better shows up, featuring [this weird trick that will make your URLs disappear](http://stackoverflow.com/questions/23571013/how-to-remove-url-from-a-string-completely-in-javascript).
=> Quickfix #178: filter out URLs from paragraphs when checking for well-formed dates

lib/profiles/IG-NOTE.js, lib/rules/sotd/stability.js, test/all-rules.js, test/docs/headers/ig-note.html
That PR:
- fixes the stability check for IG Notes
- removes the PP check for IG Notes as specified in
[pubrules](http://www.w3.org/2005/07/pubrules?year=2015&uimode=filter&filter=Filter+pubrules&filterValues=form&docstatus=ig-note-tr&rectrack=no&prevrec=doesnotapply&normative=doesnotapply&patpol=w3c#docreqs)
- adds related tests
Fix #191
=> IG Notes stability and pp checks

lib/l10n-en_GB.js, lib/l10n-es_ES.js
[The beginnings of five lines in two files were truncated by accident](https://github.com/w3c/specberus/pull/160/files#diff-641584ec6af0da9aefd9d3d07cfcf2d1L150), possibly during merges and rebases of that branch.
=> Fix copy removed accidentally around PR #160

.travis.yml
This doesn't fix [your recent issue](https://github.com/travis-ci/travis-ci/issues/4197#issuecomment-123582302) but at least it makes sure that the deployment is not run twice each time, the second one always failing.
=> Only deploy to npm when the 0.12 build ends

lib/rules/links/compound.js, lib/rules/structure/name.js, tools/fetch-groups-db.js
Sorry, changes to adapt to the new version of Superagent weren't complete before&hellip;
In particular, this PR updates the signature of functions that are passed as callbacks to `Superagent#end()`.
=> Adapt code to Superagent 1.2.0

.gitignore, package.json
Add [JSDoc](http://usejsdoc.org/) `3.3.2` to `devDependencies`, and a script to run it. JSDoc output is not included in version control.
Usage: `npm run jsdoc`; then open `doc/api/index.html`.
=> Add JSDoc and set up output

lib/validator.js
Loading specberus directly with query params wasn't checking the document with the right parameters.
The bug comes from a string to boolean conversion where `"false"` was converted to `true`.
Fix #206
=> Fix boolean conversion causing `"false"` to be converted to `true`

lib/rules/headers/dl.js, test/all-rules.js, test/docs/headers/dl-trailing-whitespace.html
Fix #207
Fix https://github.com/w3c/echidna/issues/201
=> headers: allow trailing whitespaces in uris

app.js, lib/validator.js, public/js/specberus.js
While reviewing #229, I noticed that [the UI parameter `echidnaReady`](https://github.com/w3c/specberus/commit/b84e3f74a4d7a7f9298c3df01e751a01516e6eee) isn't treated like the others (it isn't read and written, and passed along to the validator in the same way). This may be intentional, as `Specberus` doesn't really need that chunk of information at the moment. But for consistency, and to ensure the validator has access to that too should it need it in the future, I think it's best to pass it along.
(While at it, I also simplified [@deniak's boolean expressions](https://github.com/w3c/specberus/commit/13ef49b372c3defb390ddc8831b6f5756bc93c61), keeping his fix.)
=> Read and write, and pass parameter “echidnaReady” to the validator, too

lib/rules/sotd/process.js, public/index.html
Fix something that I missed in #220: the 3 processes (2005, 2014, 2015) were visible on the UI by mistake. This PR removes 2014.
=> Remove “process 2014” from the options in the UI

package.json
Major `nsp` upgrade and minor update of `socket.io` (still reports a vulnerability though).
```
┌───────────────┬───────────────────────────────────────────────────────────────────────────────────────────────┐
│               │ Regular Expression Denial of Service                                                          │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────┤
│ Name          │ ms                                                                                            │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────┤
│ Installed     │ 0.6.2                                                                                         │ …
```
=> upgrade nsp and socket.io

app.js
Apparently, some new TLDs aren't accepted by [insafe](https://github.com/w3c/insafe) because they return HTTP `406` (?). See w3c/insafe#8 and w3c/Mobile-Checker#115.
Lacking a better explanation, this patch tells `insafe` to accept that HTTP code.
=> Make “insafe” accept HTTP code 406 as valid

package.json
`master` builds [are broken](https://travis-ci.org/w3c/specberus/builds/90309652) because of [a vulnerability in package `ms`](https://nodesecurity.io/advisories/46).
This is a temporary fix so that Travis builds are again meaningful for us, until these PRs are reviewed:
* socketio/engine.io#365
* socketio/engine.io-client#433
* socketio/socket.io#2316
* socketio/socket.io-adapter#32
=> Temporary fix for https://nodesecurity.io/advisories/46

lib/exceptions.json
I assume this is the right syntax for copyright extensions based on what I've gathered from https://github.com/w3c/specberus/issues/187
=> Document approved exceptions to copyright statement for two WebRTC specs

.travis.yml
The latest tag [wasn't published automatically to npm](https://travis-ci.org/w3c/specberus/builds/94616761#L1702) because `.travis.yml` has an outdated Node.js version.
Replacing that with `node` [as recommended in the docs](https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Choosing-Node-versions-to-test-against) &ldquo;to run using the latest stable releases&rdquo;
=> Travis: build (and publish) always with latest stable Node.js

lib/rules/sotd/supersedable.js, package.json
npm has been throwing these errors for a long time:
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
`CSSselect` and `CSSwhat` have not changed in ca. two years; `lodash` was stuck at a major version that is marked as deprecated. All these three are dependencies of `whacko`.
I submitted a couple of PRs for `whacko` to get this updated; those were promptly merged, and a new version of `whacko` published to npm (the previous one was eight months old). This PR incorporates that change in Specberus.
There was an issue with the new package `css-select`. My solution is to replace `$.find('> …
=> Fix three deprecated packages

package.json
&hellip;as we did [in Echidna](https://github.com/w3c/echidna/pull/239#issuecomment-161987462).
While at it, update all dependencies to their latest (working) version.
=> Fix versions of all dependencies, up to “minor”

lib/rules/style/sheet.js, test/docs/echidna/automated-wg.html, test/docs/headers/dl-trailing-whitespace.html, test/docs/headers/ig-note.html, test/docs/headers/joint-publication-fail.html, test/docs/headers/joint-publication.html, test/docs/headers/permissive-doc-license.html, test/docs/headers/simple-oxford.html, test/docs/headers/simple.html, test/docs/headers/wrong-urls.html, test/docs/style/style-not-last.html
Note it's `w3.org/StyleSheets/TR/2016/` (not `w3.org/TR/StyleSheets/2016/` like the original issue said). This final URL is taken from our latest exchanges by e-mail.
@TODO: **[the CSS files](https://github.com/w3c/tr-design/tree/gh-pages/src) have to be deployed to that location before this milestone** (29 Jan 2016).
cf. #267.
=> Check new expected CSS location

lib/l10n-en_GB.js, lib/l10n-es_ES.js, lib/profiles/base.js, lib/rules/style/script.js, test/all-rules.js, test/docs/headers/fixup.html
Notes/questions (don't merge until these are addressed):
&rarr; **Update (19 Jan)**: confirmed after chatting with @deniak and @plehegar that we're *checking* this, not *adding* it to the spec.
&rarr; **Update (16 Feb)**: confirmed the location; cf. [`tabatkins/bikeshed#569#issuecomment-184607100`](https://github.com/tabatkins/bikeshed/issues/569#issuecomment-184607100).
@TODO: **[the script](https://github.com/w3c/tr-design/blob/gh-pages/src/fixup.js) has to be deployed to that location before this milestone** (29 Jan 2016).
cf. #267.
=> Check new expected script, “fixup.js”

lib/l10n-en_GB.js, lib/l10n-es_ES.js, lib/profiles/base.js, lib/rules/headers/secno.js, test/all-rules.js, test/docs/headers/proper-secno.html
Kind of *heuristically*.
NB: throws only a warning if no instances found, ie this rule does *not* fail.
cf. #267.
=> Check presence of <span class="secno"> in TOC/headings

lib/l10n-en_GB.js, lib/l10n-es_ES.js, lib/profiles/base.js, lib/rules/style/back-to-top.js, test/all-rules.js, test/docs/headers/back-to-top.html
NB: throws only a warning if not found, ie this rule does *not* fail.
cf. #267.
=> Check expected back-to-top link

lib/l10n-en_GB.js, lib/l10n-es_ES.js, lib/rules/structure/display-only.js
NB: adds 3 new `info` messages to the output; this rule does *not* fail.
cf. #267.
=> Emit new informative messages regarding recommended markup

lib/exceptions.js, lib/exceptions.json
`exceptions.json` now takes regexp for shortnames.
=> Generic exceptions

lib/validator.js, test/docs/headers/h2-comma.html
[This test](https://github.com/w3c/specberus/blob/master/test/all-rules.js#L82) passes (wrongly) just because [`Specberus.docDateEl` keeps its value from the last validation](https://github.com/w3c/specberus/blob/master/lib/validator.js#L168-L189) (wrongly).
This PR makes sure that property is reset every time Specberus' cache is cleared, and updates the test document to make it valid.
=> Reset Specberus.docDateEl when clearing the cache

lib/rules/metadata/rectrack.js, test/docs/metadata/charmod-norm.html, test/rules.js
Two suggestions:
* Update documentation comment and remove obsolete constants.
* Make the new regex more robust, and make the sample doc a bit tougher.
Feel free to pick and choose, @deniak.
=> Suggestions to #311

README.md, lib/profiles/metadata.js, lib/rules/metadata/rectrack.js, test/docs/metadata/charmod-norm.html, test/rules.js, test/samples.json
`extractMetadata` now detects whether the document is on REC-track or not.
The goal is to pass that information to Echidna so it can also publish document on Note-track.
=> extractMetadata rectrack

lib/rules/validation/css.js, lib/rules/validation/html.js
* check if the HTML/CSS validators respond before processing the result
* remove unreachable `else if (!json)`
Fix https://github.com/w3c/echidna/issues/279
=> Process superagent errors after calling the validators

lib/exceptions.json
@dontcallmedom, since most of the exceptions are for the specs from the DAP WG, do mind reviewing that one?
=> clean exceptions now that the CSS validator handles calc()

README.md, lib/profiles/metadata.js, lib/rules/echidna/editor-ids.js, lib/rules/headers/dl.js, lib/rules/headers/h1-title.js, lib/rules/metadata/dl.js, lib/rules/metadata/docDate.js, lib/rules/metadata/editor-ids.js, lib/rules/metadata/informative.js, lib/rules/metadata/process.js, lib/rules/metadata/title.js, lib/rules/sotd/process.js, lib/validator.js, test/docs/metadata/components-intro.html, test/rules.js, test/samples.json
`extractMetadata` takes care of extracting all the metadata needed. There is still an event metadata `shortname` but it's only needed in the exception system. I'll see how to change that in another PR.
=> Handle all the metadata in `extractMetadata`

README.md, public/js/specberus.js
* Fix a JS bug.
* JSON mandates `"` for strings.
=> Batch of minor fixes

lib/rules/links/compound.js
=> Fix: rule “links/compound” relies on “Specberus.url”

lib/rules/headers/dl.js, lib/rules/metadata/dl.js, lib/validator.js
That PR fixes the same day publication check as `extractHeaders` is now defined in `Specberus`.
=> fix extractHeaders on the same day publication check

lib/l10n-en_GB.js, lib/l10n-es_ES.js, lib/rules/headers/h2-toc.js
More than one `<h2>` inside `<nav id="toc">` is now permitted, as long as exactly one matches `/^table\s+of\s+contents$/i`.
Fixes #351.
=> Make ToC detection more accurate

README.md, app.js, lib/api.js, lib/sink.js, lib/util.js, lib/validator.js, package.json, test/api.js
This PR sets up a REST API using Express, with 3 methods:
* `version`
* `metadata`
* `validate`
And adds a test file for Mocha with placeholders for API tests.
Because this functionality was moved here from branch `tripu/metadata`, there are a few files in common (`sink.js`, `util.js`, `samples.json`). Those should be OK when we merge the branches.
As the API relies on the new method `Specberus.extractMetadata()`, **do *not* merge this before #299**; it won't work.
**TO-DO:** [Updated 3/May/2016]
* ~~Write the tests. My plan is to launch the Specberus server locally first, then use `superagent` to throw a few requests at it, and check the results.~~ :ballot_box_with_check:
* ~~POST or GET? Method `version` should be GET. I'm not sure about the other two.~~ :ballot_box_with_check: All are …
=> Set up REST API

README.md, lib/l10n-en_GB.js, lib/l10n-es_ES.js, lib/rules/sotd/group-homepage.js, lib/validator.js
* Readapt rule `sotd.group-homepage` to the new way of throwing messages.
* Enforce requirement of new env var `API_KEY`: Specberus throws an exception if not defined. Works both as Node.js module and as an independent application. Only checks that the variable exists and that it is not an empty string. I have added [a bogus value in Travis](https://travis-ci.org/w3c/specberus/jobs/133116201#L142) so that tests pass there.
* More informative error message (I think). &hellip;that should never appear because of the enforcement above. Also, unify both L10n files (even if we plan to discard one of them anyway).
* Small fixes in README; formatting and env vars.
=> Improvements over #361

lib/l10n.js
Since the echidna profiles are not standard, use the related profile to display error messages
Fix #377
=> Errors and rule descriptions for echidna profiles

lib/rules/sotd/cr-end.js
Fix:
```
/specberus/lib/rules/sotd/cr-end.js:14
sr.info(self, "date-found", {date: res.toDateString()});
^
TypeError: Cannot read property 'toDateString' of undefined
at Object.exports.check (/specberus/lib/rules/sotd/cr-end.js:14:43)
at /specberus/lib/validator.js:116:18
at Array.forEach (native)
at doValidation (/specberus/lib/validator.js:112:23)
at Specberus.loadSource (/specberus/lib/validator.js:383:5)
at /specberus/lib/validator.js:369:18
at Request.callback (/specberus/node_modules/superagent/lib/node/index.js:691:12)
at IncomingMessage.<anonymous> (/specberus/node_modules/superagent/lib/node/index.js:922:12)
at emitNone (events.js:91:20)
at IncomingMessage.emit (events.js:185:7)
```
(The build fails in Travis [for Node v4 …
=> Fix “undefined property” runtime error in “cr-end” rule

lib/rules/links/compound.js, lib/rules/validation/css.js, lib/rules/validation/html.js, public/js/specberus.js
If the option 'recursive validation' is selected and the document doesn't contain other pages, the validation never ends.
That PR also fixes a bug on the UI if a different QS param is specified
Fix #391
=> Fix validation of compound documents

lib/rules/sotd/mailing-list.js
Some documents list the https version of the archive link, e.g. http://www.w3.org/TR/2016/CR-mediacapture-streams-20160519/
=> mailing list archive: also check https

lib/rules/sotd/group-homepage.js, lib/validator.js, views/layouts/main.handlebars
* `s/specberus/pubrules/gi`: fix last occurrences of `specberus` in the output, and consolidate the new UA string introduced by #393.
* Fix meta `keywords` in main Handlebars layout.
* The long title was too long IMHO. When the version and the page title are appended, it takes too much space in the window title bar, and it is wrapped on the header of the page so part of it isn't visible. This is a proposal. If the long one *has* to be displayed, I'll rearrange the layout of the header.
* Fix TypeError:
```
Uncaught TypeError: Cannot read property 'status' of undefined
at lib/rules/sotd/group-homepage.js:36:57
at Request.callback (node_modules/superagent/lib/node/index.js:592:12)
at ClientRequest.<anonymous> (node_modules/superagent/lib/node/index.js:544:10)
at …
```
=> Omnibus PR

lib/exceptions.js, lib/exceptions.json
@tabatkins @ylafon, that PR makes specberus ignore the SVG errors reported by the CSS validator. 
I did it that way because I expect it will require a lot of work to implement all the SVG properties in the validator. Here's the list of properties that will be skipped:
* `fill`
* `fill-opacity`
* `text-anchor`
* `stroke`
* `stroke-width`
* `stroke-dasharray`
This is a non-exhaustive list but I believe it'll enough for the specs generated by bikeshed.
@ylafon I assigned you as the reviewer to get your input on how we are going to handle these errors.
=> SVG errors reported by the CSS validator are treated as exceptions

lib/profiles/metadata.js, lib/rules/metadata/dl.js, lib/rules/metadata/editor-names.js, lib/validator.js, test/rules.js, test/samples.json
If the document doesn't contain any `data-editor-id`, it's useful to know which editors appear on the spec.
=> Metadata: extract editors' names

public/js/specberus.js
* Whole form is disabled (greyed-out) and text of button changes (from &ldquo;check&rdquo; to &ldquo;wait&hellip;&rdquo;) if there's a validation running. Prevents against clicking more than once. Fixes #149.
* When the socket disconnects, reload the page (fixes #399).
* When there are query parameters and validation occurs automatically, do so by actually submitting the form (instead of just sending stuff through the socket). Makes it consistent with the changes above (form is disabled), and hopefully will solve situations where validation isn't triggered automatically now&hellip; (not sure; I'll have to keep on testing that).
* Progress bar returns to 0 once validation finishes (prevents that effect when the progress bar appears to go backwards).
=> Prevent redundant run; monitor socket status

lib/api.js
The `rectrack` param is not properly retrieve from the JSON.
=> fix bug on rectrack param in the validation API

lib/l10n-en_GB.js, lib/rules/sotd/ac-review.js, lib/rules/sotd/charter-disclosure.js, lib/rules/sotd/implementation.js, lib/rules/sotd/mailing-list.js, lib/rules/sotd/pp.js, lib/rules/sotd/process-document.js, lib/rules/sotd/review-end.js, lib/rules/sotd/stability.js, lib/rules/sotd/status.js, lib/rules/sotd/submission.js, lib/rules/sotd/supersedable.js, lib/rules/sotd/team-subm-link.js, lib/validator.js, test/docs/heuristic/dated-url.html, test/docs/heuristic/dates.html, test/l10n.js
Absence of a proper SotD section throws one error only, the first time it's searched for in `validator.js`; rules calling `Specberus.getSotDSection()` don't throw that error themselves.
eg, if one checks `http://example.com/` as a WD, 4 redundant error messages are removed after this change.
Fix #462.
=> Fix duplicate “no SotD section” error messages

public/js/specberus.js, views/index.handlebars
@deniak, this is my first take, but I'm not sure. Let me know your thoughts.
When the socket disconnects, a modal appears, informing the user of what just happened. Users can either dismiss and continue examining the results of validation, or reload the page if they finished reading the results already.
The modal won't bother the user a second time (not unless they reload the page and validate a document again).
I like this approach. The problem is, if connection through the socket is interrupted quite often (as it seems; I don't know why), it's a matter of (little) time that users will see this pop-up. I fear it will be annoying and interrupt the user while they're reading the results.
I may not be listening to the correct socket event, too.
Fix #479.
=> Prevent Specberus from reloading the page automatically when connection to the server is lost

public/js/specberus.js
cf https://github.com/w3c/specberus/pull/486#issuecomment-239391818
=> Prevent "socket disconnected" modal from appearing in FF when navigating away following a link

app.js, lib/l10n-en_GB.js, lib/l10n.js, lib/rules/metadata/process.js, public/js/specberus.js, test/docs/metadata/components-intro.html, test/samples.json
* Metadata extraction can now throw errors and warnings, like validation does, and those are captured by the application.
* Those events are shown on the web UI too, including rule desriptions and &ldquo;see rule in context&rdquo; and &ldquo;report a bug&rdquo; links (if pertinent).
* Throw an error if the process document isn't found (this fixes #501).
* One test document tweaked to fix this new error in it.
**Merge #504 before this one** (that PR is against this branch, not against `master`).
=> Enable errors and warnings from metadata extraction; alert if process document is not found

lib/l10n-en_GB.js, lib/rules/metadata/dl.js
Fixes #508.
The build fails because this change relies on the ones made in PR #503 (allowing metadata extraction to throw errors, and splitting 'meta' in `l10n-en_GB.js` into several categories). This PR should be merged *after* that one, and the contents of `l10n-en_GB.js` merged appropriately.
=> Fix "TypeError: Cannot read property '1' of null"

public/js/specberus.js
Looks like this:
(If it's too intrusive, we can limit its height, like this:
Although I prefer not to: scrollbars within scrollbars are annoying and not a good practice.)
Fixes #301.
**Merge before #503** (this goes on top of those changes).
=> When auto-detecting, show also extracted metadata in result table

.nsprc
socket.io has been upgraded to 1.5.0 which fixes vulnerabilities #106 and #120
=> NSP exceptions are no longer needed

lib/l10n-en_GB.js
=> Mention in output common "HTTP vs HTTPS" errors with boilerplate URLs

lib/l10n-en_GB.js, lib/rules/sotd/supersedable.js
Link to corresponding section on publication rules page, and mention HTTP<del>S</del> as a likely error.
Fixes #535.
=> Improve error messages thrown by “sotd.supersedable”

lib/l10n-en_GB.js, lib/rules/headers/dl.js, lib/rules/sotd/pp.js, test/docs/headers/wrong-urls.html
* Add better context to one particular error, to be shown on results page when it occurs
* Simplify a long regex (and adapt logic accordingly); cf https://github.com/w3c/specberus/pull/559#pullrequestreview-13297525
About the latter: change is covered by tests ([old](https://coveralls.io/builds/9313910/source?filename=lib%2Frules%2Fheaders%2Fdl.js#L132), [new](https://coveralls.io/builds/9315355/source?filename=lib%2Frules%2Fheaders%2Fdl.js#L132)), and the new regex behaves as expected ([old diagram](https://jex.im/regulex/#!embed=false&flags=&re=%5E(https%3F%3A%5C%2F%5C%2Fwww%5C.w3%5C.org%5C%2FTR%5C%2F%5Cd%7B4%7D%5C%2F%5BA-Z%5D%2B-(.%2B)-(19%5Cd%7B6%7D%7C200%5Cd%7B5%7D%7C201%5B0-5%5D%5Cd%7B4%7D%7C20160%5B1-7%5D%5Cd%7B2%7D)%5C%2F%7Chttps%3A%5C%2F%5C%2Fwww%5C.w3%5C.org%5C%2FTR%5C%2F%5Cd%7B4 …
=> Miscellaneous improvements

lib/rules/sotd/pp.js, test/docs/sotd/joint-publication.html
=> joint publication detection: use non-greedy regex to catch the right WG names

.jshintrc, lib/util.js
* Use [`fs.readdirSync()`](https://nodejs.org/dist/latest-v6.x/docs/api/fs.html#fs_fs_readdirsync_path_options) instead to traverse the filesystem in search of profiles. (Bad idea in general to opt for synchronous methods, but there would be too many ramifications down the line if we were to defer the value of `exports.profiles` in this module&hellip;)
* `` `${__dirname}/profiles/` `` instead of `'./lib/profiles/'` for better portability.
=> Avoid asynchronous “fs.readdir” and non-portable paths

lib/validator.js
@plehegar your [earlier commit](https://github.com/w3c/specberus/commit/a6c6594dad3d99de8069c3bfffb75559565c9255#diff-b973211993289ad59465118eecb30110) limits the exceptions to WDs and CRs only.
How about adding notes too? FYI, this is preventing some people to publish with echidna
=> Notes can also take advantage of exceptions

public/js/scroll-tweak.js, public/js/specberus.js
[Safari seems to be mostly okay now; Opera Mini and older Android native browsers (not widely used) are the remaining offenders](http://caniuse.com/#feat=const). So, strict mode and no `const`. (And still avoiding fat arrow functions, as [support isn't universal yet](http://caniuse.com/#feat=arrow-functions).)
Fixes #502.
=> Client-side JS: switch to strict mode and avoid use of “const”

public/js/scroll-tweak.js
I think I have improved the JS logic that prevents selected fragment IDs from being aligned at the very top of the viewport and therefore obscured by the header overlay.
Now, the fragment ID (if there is one) should be shown near the middle of the viewport (after a delay of 500 ms and provided that the user has *not* scrolled the page manually already, to prevent jitters and any confusing behaviour).
Also, now this works too when clicking hashes: the page will scroll and the selected rule will be in the middle.
Fixes #538.
=> /doc/rules/: fix scroll of selected fragment ID

lib/rules/links/compound.js
How to reproduce: validate recursively a page that contains at least one hyperlink that can't be resolved; a RTE will occur and the application will crash.
(For example: [`https://r12a.github.io/scripts/tutorial/`](https://r12a.github.io/scripts/tutorial/) has near the top a link (text: &ldquo;intended audience&rdquo;) where the author forgot to include the `#` at the beginning (it's supposed to be a fragment ID), so instead it's interpreted as a link to `https://r12a.github.io/scripts/tutorial/audience`, which does not exist.)
This should solve the issue.
=> Fix critical bug (causes a crash) when recursively validating page with broken links

views/doc/index.handlebars
Relative links on the [pubrules documentation page](https://www.w3.org/pubrules/doc/) to the different profiles are broken.
I think this fixes the issue.
=> Fix relative links to profile rules

lib/rules/headers/copyright.js, test/docs/headers/copyright-freedom.html, test/docs/headers/simple-oxford.html, test/docs/headers/simple.html
The current regex won't return an error on copyrights like:
```
Copyright © 2017 FOOBAR & W3C® (MIT, ERCIM, Keio, Beihang). W3C liability, trademark and permissive document license rules apply. 
```
These cases should be handled as exceptions.
=> update the copyright regex to avoid dummy copyrights

.travis.yml, package-lock.json, package.json
* v4 is superseded and too old.
* v5 deprecated.
* v8 is the new LTS version.
cf [`github.com/nodejs/LTS`](https://github.com/nodejs/LTS#lts-schedule)
**In or around 1 Apr:** restart the Travis build, test & confirm, merge.
=> Adapt to Node.js release schedule

app.js, package.json
As far as I can tell, we don't seem to be using it.
Closes #668.
=> Remove package “body-parser”

lib/l10n-en_GB.js, lib/profiles/base.js, lib/rules.json, lib/rules/structure/canonical.js, test/docs/structure/canonical-href-missing.html, test/docs/structure/canonical-missing.html, test/docs/structure/canonical.html, test/rules.js
Starting from Oct 1, we will require a `rel=canonical`.
See https://lists.w3.org/Archives/Public/spec-prod/2017JulSep/0005.html for more details.
=> Link rel=canonical

.nsprc
`express`: [the issue](https://nodesecurity.io/advisories/535) in `mime` [is fixed](https://github.com/broofa/node-mime/issues/167), and both `mime` and `send` are upgraded. But `express` [has not picked it up yet](https://github.com/expressjs/express/issues/3431). Thus, muting for the time being.
cf #684
=> Mute a new nsp error

README.md, views/help.handlebars, views/index.handlebars
Specifically, addresses https://github.com/w3c/specberus/issues/705#issuecomment-343625898
Fixes #705
=> Mention w3.org/pubrules API endpoint in the documentation

lib/exceptions.json
It was suggested that we skip the CSS validation or at least ignore the errors for the CSS specs.
That PR adds that exception for all the specs with a shortname starting with `css`.
/cc @svgeesus
=> Skip CSS validation for the CSS specs

lib/l10n-en_GB.js, lib/profiles/TR/WG-NOTE.js, lib/rules.json, lib/rules/sotd/deliverer-note.js, lib/rules/sotd/delivererNote.js, lib/rules/sotd/pp.js, lib/validator.js, test/docs/headers/wg-note.html, test/docs/metadata/csvw-ucr.html, test/docs/sotd/note-deliverer-bad.html, test/docs/sotd/note-deliverer.html, test/rules.js
Based on a discussion with @wseltzer .
New wording for WG Note should only be:
[[
This document was produced by a group operating under the W3C Patent Policy.
]]
(and nothing else following)
=> Groupnote pp

lib/exceptions.json
These exceptions were deployed in production but we missed the update in the repository
=> more exceptions

lib/rules.json
I just noticed https://github.com/w3c/specberus/pull/707 was incomplete. It's missing the update on the rule description regarding the patent policy for Notes.
=> update rule description on patent policy boilerplate

lib/rules/metadata/dl.js
That metadata will be used in Echidna to detect if it's an updated document or not.
=> new metadata to detect if a document was already published

known-vulns.txt, package.json
The issue was a recent switch from vulns of the form
`https://nodesecurity.io/advisories/xxx`
to
`https://npmjs.com/advisories/xxx`
:P
This should fix it.
Closes #796
=> 'npm run audit': make more robust (improve regex)

lib/rules.json
Include this source code:
`<script src="//www.w3.org/scripts/TR/2016/fixup.js" type="applicationjavascript"></script>`
should read instead
Include this source code:
`<script src="//www.w3.org/scripts/TR/2016/fixup.js" type="application/javascript"></script>`
=> Properly escape / for application/javascript

lib/exceptions.json
[[
Content of title and h1 do not match.
The document's title must be in the title element and in an h1 element.
]]
from [pubrules](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2019%2FWD-webauthn-2-20191126%2F&profile=WD&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004)
cc @akshayku @wseltzer
=> webauthn-2 use markup in its <h1> element

lib/api.js, lib/sink.js, lib/validator.js
suggedted by @sidvishnoi in https://github.com/w3c/specberus/issues/706.
We actually rely on the 2 `emit` params for the documentation so I ended up merging both of them in the listeners.
Does that solve your issue @sidvishnoi ?
=> flatten event params for err, warning and info

.github/dependabot.yml
Will bump GitHub Actions version like `actions/setup-node` to later versions on the same schedule as the other Dependabot updates
=> chore: Add GitHub Action Dependabot bumping

lib/l10n-en_GB.js
Proposal to use https link for validator.w3.org ones.
During checking by pubrules for /TR/ publishing, I've noticed that an notice of link check points to http://validator.w3.org .
=> use https for validator.w3.org

app.js
=> Fix crash when upgrade to socket.io 3.0.0

lib/exceptions.json, lib/rules/headers/h1-title.js, lib/rules/metadata/title.js
Some specs (eg. [webauthn-2](https://www.w3.org/TR/2020/WD-webauthn-2-20201116/) have titles contains breaking lines. jsdom simply strips them which breaks the title scrapping.
The PR tries to format the title correctly.
=> title: format title containing <br>

.eslintrc.json, lib/api.js, lib/l10n.js, lib/rules/style/meta.js, lib/util.js, lib/views.js, package.json
- Only added for the server-side JS files
- It can cleanup and stub in a bunch of the `@TODO` functions by running `npm run lint -- --fix`, but it would increase the number of warnings since it can't auto fix the type or a description
=> chore: Add eslint-plugin-jsdoc

.github/workflows/js-lint.yml, .github/workflows/node.js.yml
Allows the linting to run for external forks without trying to resolve the issue around the tests requiring the SECRET in the nodejs.yml job.
The JSDoc part could also probably be moved to a separate job with a smaller `paths` target, and upload the results
=> chore: Pull JS linting to separate CI job

lib/rules/metadata/profile.js, lib/views.js
resolves #1234 with reporting error:
> Pubrules is having a hard time identifying the profile of the document @@docTitle from its &lt;h2&gt;. Please make sure the &lt;h2&gt; is in a valid format: <pre><code>&lt;h2&gt;W3C (type of the document) DD Month YYYY&lt;/h2&gt;</code></pre>
see screenshot:
=> Report better error if the document is TR but not valid (cannot find profile)

public/js/specberus.js
The patentPolicy metadata still returns the first PP link. So there's no need for UI to treat patentPolicy as array.
https://github.com/w3c/specberus/blob/f92b6181014a0800334e278b64cc06a37c23c5dd/lib/rules/metadata/patent-policy.js#L9-L12
=> Fix UI for patent policy

lib/l10n-en_GB.js, lib/rules/headers/dl.js, test/docs/headers/dl-mismatch.html, test/docs/headers/dl-no-implelink.html, test/docs/headers/dl-order.html, test/docs/headers/dl-untrimmed-text.html, test/docs/headers/fails.html, test/rules.js
resolves #1080. The rule is described in https://github.com/w3c/specberus/issues/1080#issuecomment-888856289
=> Allow CR&REC to not have implementation report

.gitignore, README.md, app.js, lib/api.js, lib/rules/metadata/dl.js, lib/rules/metadata/profile.js, lib/rules/sotd/group-homepage.js, lib/rules/sotd/pp.js, lib/validator.js, test/api.js, test/rules.js
Refactored code to better support Node API:
- `apiKey` is required when creating `new Specberus` instance (instead of when importing).
- Specberus instance doesn't rely on `process.env`
- `process.env.W3C_API_KEY` is required only in tests and server.
- `process.env.BASE_URI` is required only in server.
- Avoiding API breaking change by using `process.env.W3C_API_KEY` as
default during construction.
Closes https://github.com/w3c/specberus/issues/783
Ref: Adding specberus to spec-prod GitHub action (https://github.com/w3c/spec-prod/pull/100)
=> Require apiKey in Specberus constructor instead of env

package.json, test/rules.js
Will warn as old inline disabled sections are no longer required from parent config or code changes
=> chore: Remove and lint unused ESLint ignores

.husky/pre-commit, package.json
Makes the current commit hook a little faster by just running the linting and spellchecking on files being changed, and auto fix the ESLint issues
=> chore: Use lint-staged for husky

.github/workflows/js-lint.yml, .github/workflows/node.js.yml, .github/workflows/spelling.yml, .gitignore, package-lock.json
Unignored and regenerated a fresh lockfile with no NPM audit issues.
With the lockfile, CI can use the build-in NPM caching during the builds and helps repeatability.
=> chore: Add lockfile and use NPM caching in CI

.cspell.json, package.json
The newer schema is `0.2`, but shouldn't affect any of the current config.
Expanded the glob and ignored the new issues flagged in the `design` folder
=> chore: update cSpell glob and schema

.github/workflows/js-lint.yml, .github/workflows/node.js.yml, .github/workflows/spelling.yml
Should remove any Dependabot updates till there is a new major version
=> ci: unpin actions/checkout to v2

package-lock.json, package.json
Was previously required for the husky install scripts.
Husky now uses `prepare` instead of `postinstall`
=> chore: remove pinst

.github/dependabot.yml
Keeps the reduced noise from the weekly semver-patch restricted PRs, but
with a monthly catchup for the patches
=> chore: Allow Dependabot semver patch monthly

.github/workflows/node.js.yml
- ignore the Dependabot branches on push to avoid double building
- restrict the secrets/token to read-only
- don't persist github credentials when checking out PRs
=> ci: allow testing on non-dependabot PRs

.github/workflows/js-lint.yml
Unlike the CI testing, linting only really needs to be run once, since the node version shouldn't matter beyond the `engine` support used by eslint-plugin-node which doesn't matter the version it's run on
=> ci: only lint on the current LTS used by actions

.prettierignore
Doesn't really slow it down as there isn't much in the directory from the code coverage generation
=> chore: ignore nyc coverage dir from prettier

.eslintrc.json
It's still in the devDependencies, but wasn't actually configured right now
=> chore: re-add eslint-plugin-jsdoc

package.json
They didn't seem to be grouped in a particular order, so alphabetical is a little easier to find a script instead
=> chore: sort NPM scripts

.eslintrc.json
Few rules now have no violations and don't seem like specific style choices anymore
=> chore: remove passing ESLint suppressions

.eslintrc.json, lib/rules/links/linkchecker.js
This was the only warning for the rule, so I reenabled it and saw that this was actually using a private field instead of the public function
=> fix: don't use intenral puppetter field

views/doc/index.handlebars
Noticed this because pretty was crashing trying to parse it. The other reference to these URIs don't have that relative path in the front, so I dropped it
=> fix: relative path before BASE_URI

lib/rules/links/linkchecker.js
Browsers logos are now available on our cdn, e.g. https://cdn.w3.org/assets/logos/w3c/browser-logos/android-webview-beta/android-webview-beta.png.
The PR allows the use of these logos
Fix #1543
=> allow links to cdn.w3.org/assets

lib/rules/links/linkchecker.js
That PR adds a trailing slash to some of the allowed asset URLs.
=> add trailing slashes on allowed assets urls

lib/rules/headers/dl.js
Some specs may list the whole group as editor. In this case, there's no editor ID.
This PR adds an exception for Working|Interest groups.
https://github.com/w3c/deviceorientation/issues/100
=> allow groups as editors

lib/exceptions.js, lib/exceptions.json
We now rely on validator.nu to report CSS errors. That PR updates the exception system to "ignore" these errors as it was already done when the check was done with the CSS validator.
=> add exception for all the CSS errors reported by the validator.nu

.cspell.json, package.json, test/lib/nockData.js, test/lib/testserver.js, test/lib/utils.js, test/rules.js
- Add testserver, run by `npm run testserver` to host all the test documents. `npm run testserver` points to test/lib/testserver.js that can run independently
- simplify `test/rules.js file`: 
1. move testserver into test/lib/testserver.js
2. move common functions into test/lib/util.js
3. move nock config into test/lib/nockData.js
=> Add independent testserver

lib/rules/sotd/stability.js
If there's a breaking line between "wide" and "review", the test will fail. That PR addresses that issue.
=> normalize text before filtering

lib/rules.json, lib/rules/sotd/pp.js, lib/rules/sotd/stability.js, lib/util.js, lib/validator.js, test/data/TR/Note/NOTE.js, test/doc-views/TR/Note/noteBase.js, test/doc-views/partials/stability.handlebars, test/doc-views/specBase.js
Allow both sentence A and B in DNOTE and NOTE:
A: This Group (Draft )?Note is endorsed by the XXX Group, but is not endorsed by W3C itself nor its Members.
B: Group (Draft )?Notes are not endorsed by W3C nor its Members.
For case A, also support joint publication: 
> This Group (Draft )?Note is endorsed by the AA Working Group and the BB Working Group, but is not endorsed by W3C itself nor its Members.
resolves #1075
=> Add note-stability sentence

.cspell.json, app.js, lib/l10n-en_GB.js, lib/profiles/TR/Note/DNOTE-Echidna.js, lib/profiles/TR/Note/NOTE-Echidna.js, lib/profiles/TR/Recommendation/CR-Echidna.js, lib/profiles/TR/Recommendation/CRD-Echidna.js, lib/profiles/TR/Recommendation/REC-Echidna.js, lib/profiles/TR/Recommendation/WD-Echidna.js, lib/rules/echidna/deliverer-change.js, test/data/TR/TRBase.js, test/doc-views/TR/Note/DNOTE-Echidna.js, test/doc-views/TR/Note/NOTE-Echidna.js, test/doc-views/TR/Recommendation/CR-Echidna.js, test/doc-views/TR/Recommendation/CRD-Echidna.js, test/doc-views/TR/Recommendation/WD-Echidna.js, test/doc-views/TR/TRBase.js, test/lib/nockData.js, test/rules.js
Add rule deliverer-change to echidna files, resolves https://github.com/w3c/echidna/issues/581
- Use W3C API to get previous version's deliverer id
=> Add rule to detect echidna deliverer change

lib/validator.js
In the past, we only allowed rule exceptions for WD, Notes, CR, CRD and DRY.
Looking at the current exceptions, I think that restriction can now be removed.
This will allow the publications of some edited RECs (that have an exception) with echidna.
@plehegar, how does that sound?
=> allow exceptions for all profiles

package-lock.json, package.json
Reverts w3c/specberus#1722
The new puppeteer version actually breaks specberus:
```
specberus/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:118
return callback.promise.finally(() => {
^
TypeError: callback.promise.finally is not a function
at CallbackRegistry.create (specberus/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:118:40)
at Connection._rawSend (specberus/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:212:26)
at Connection.send (specberus/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:206:21)
at new ChromeTargetManager (specberus/node_modules/puppeteer-core/lib/esm/puppeteer/common/ChromeTargetManager.js:234:14)
at new CDPBrowser (specberus/node_modules/puppeteer-core/lib/esm/puppeteer/common/Browser. …
```
=> Revert "chore(deps): bump puppeteer from 19.7.1 to 19.8.2"

package-lock.json, package.json
The new version of insafe removes the dependency to [when](https://www.npmjs.com/package/when) which conflicts with the recent versions of puppeteer.
=> upgrade insafe

lib/rules/links/linkchecker.js
Assets are now served from www.w3.org. That PR updates the reference to cdn.w3.org
=> we no longer serve assets from cdn.w3.org

lib/exceptions.json
Discussing with @ylafon and @plehegar, the editors participation rule should not apply to the spec privacy-principles
=> ignore editors participation for privacy-principles

lib/copyright-exceptions.json
This PR adds custom copyright line for HTML Ruby Markup Extensions.
Here's the context which makes this necessary and appropriate:
The Licensing section of the charter of the HTML-WG (https://www.w3.org/2022/06/html-wg-charter.html#licensing) states that:
> This Working Group will use the CC-BY license, and follow the terms of
> WHATWG-W3C Memorandum of Understanding and 2021 Relationship Update
The specify CC-BY license use by HTML
(https://html.spec.whatwg.org/multipage/acknowledgements.html#ipr) is
Attribution International 4.0 (CC BY 4.0).
html-ruby-extensions is an upcoming chartered deliverable of the HTML-WG: https://www.w3.org/2022/06/html-wg-charter.html#ruby
Its content will devrive both from W3C deliverables and from the WHATWG's HTML Standard.
This publication is agreed to by …
=> Add copyright exception for Ruby markup extensions

lib/rules/sotd/stability.js
=> update stability text if there are multiple groups

.cspell.json, lib/exceptions.json, lib/rules/headers/dl.js, lib/validator.js
webgpu and WGSL are transitioning to CR but the implementation report will be published later on.
That PR adds an exception to pubrules to allow subsequent CRD publications.
I will remove the exception once the implementation report is ready.
=> add exception on implementation report for webgpu and WGSL

lib/copyright-exceptions.json
Ideally pubrules would ignore these attributes when comparing the copyright string, but hopefully this works around the issue.
=> Bikeshed adds width and height attributes to the security-privacy-questionnaire copyright image.

README.md, lib/api.js, lib/l10n-en_GB.js, lib/profiles/additionalMetadata.js, lib/rules/metadata/abstract.js, lib/rules/metadata/sotd.js, lib/util.js, lib/validator.js
Some services need to get the abstract and the SotD of TR documents.
That PR introduces a new parameter to extract these paragraphs and lists them in metadata list
=> Introducing a new parameter to get additional metadata

lib/rules/sotd/stability.js
Based on a discussion with @koalie and @plehegar, we should allow describe a statement as a "document" or a "specification".
That PR updates the stability check to allow both words
=> Statement stability: allow both document and specification wordings

lib/profiles/TR/Recommendation/DISC.js
Discontinued specs should not require the editors to be participating in the group.
/cc @svgeesus @plehegar
=> do not check editors' participation to the group producing the spec

lib/copyright-exceptions.json
Replaced deprecated copyright exceptions with updated versions.
=> shortname change for epub-a11y and epub-a11y-tech
